version: "3.8"
services:
  nginx:
    image: nginx
    depends_on: 
     - web-application
    volumes:
      - ./web-application/src/presentation-layer-api/frontend/:/etc/nginx/html
    ports:
      - 8000:80
  web-application:
    build: ./web-application
    ports:
     - 80:80
    volumes:
     - ./web-application/src:/the-web-application/src/
    depends_on:
     - redis
     - db
  db:
    build: ./db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: theRootPassword
      MYSQL_DATABASE: fanscoopDatabase
  redis:
    image: redis
    ports:
      - 6379:6379
  
  