
module.exports = {
    MIN_USERNAME_LENGTH : 5,
    MAX_USERNAME_LENGTH : 15,
    MIN_PASSWORD_LENGTH : 7,
    MAX_PASSWORD_LENGTH : 30,
    MIN_CLUBNAME_LENGTH : 3,
    MAX_CLUBNAME_LENGTH : 30,
    MIN_TITLE_LENGTH : 3,
    MAX_TITLE_LENGTH : 20,
    MIN_CONTENT_LENGTH : 5,
    MAX_CONTENT_LENGTH : 500,
    privateKey: "shhNoOneWillKnow"
}


